<?php
    $collection = $this->getTestCollection();

?>
<a href="<?php echo $block->getBaseUrl()?>insertdatathrowform/index/listing/" class="button">Go to list</a>
<div class="col-md-6">
	<div class="row">
		<div class="col-md-6">
		    <form name="addData" method="post" id="addData" class="form"
		          action="<?php echo $block->getBaseUrl().'insertdatathrowform/index/save'; ?>"
		          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
		          data-mage-init='{"validation":{}}'>
		        <fieldset class="fieldset">
		            <!-- <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend> -->
		            <fieldset class="fieldset row">
		                <div class="fields col-md-6">
		                    <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->
		                            escapeHtmlAttr(__('Name')) ?></span></label>
		                        <div class="control">
		                            <input name="name" id="name" title="Name" value="" class="input-text" type="text"
		                                   data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
		                        </div>
		                    </div>
		                    <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->
		                            escapeHtmlAttr(__('Email')) ?></span></label>
		                        <div class="control">
		                            <input name="email" id="email" title="Email" value="" class="input-text" type="text"
		                                   data-validate="{required:true, 'validate-email':true}">
		                        </div>
		                    </div>
		                    <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
		                        <div class="control">
		                            <input name="telephone" id="telephone" title="Telephone" value="" class="input-text"
		                                   type="text" data-validate="{required:true}">
		                        </div>
		                    </div>
		                      <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Gender')) ?></span></label>
		                        <div class="control">
		                            Male: <input name="gender" id="gender" title="Gender" value="Male" class="input-text"
		                                   type="radio" data-validate="{required:true}">
		                                   
		                            Female: <input name="gender" id="gender" title="Gender" value="Female" class="input-text"
		                                   type="radio" data-validate="{required:true}">
		                        </div>
		                    </div>
		                    <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Qualification')) ?></span></label>
		                        <div class="control">
		 							<select class="select" name="qualification" id="qualification" >
		 								<option value=""> </option>
		 								<option data-title="BE" value="BE">BE</option>
		 								<option data-title="MBA" value="MBA">MBA</option>
		 							</select>
		                        </div>
		                    </div>
		                    <!-- <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Qualification')) ?></span></label>
		                        <div class="control">
		 							<select class="admin__action-multiselect-wrap action-select-wrap admin__action-multiselect-tree _active" name="qualification" id="qualification" >
		 								<option value=""> </option>
		 								<option data-title="Male" value="1">BE</option>
		 								<option data-title="Female" value="2">MBA</option>
		 							</select>
		                        </div>
		                    </div> -->
		                    <div class="field name required">
		                        <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Subscription')) ?></span></label>
		                        <div class="control">
		                            <input name="subscription" id="subscription" title="Subscription" value="Yes" class="input-text"
		                                   type="checkbox" data-validate="{required:true}">
		                        </div>
		                    </div>
		                </div>
		            </fieldset>
		        </fieldset>
		        <div class="actions-toolbar">
		            <div class="primary">
		                <button type="submit" class="action submit primary" title="Save"><span><?= $block->
		                    escapeHtmlAttr(__('Save')) ?></span></button>
		            </div>
		        </div>
		    </form>
		</div>
		</div>
	</div>
</div>
